### ISSUE TITLE
what if cmdline is NULL 

### ISSUE THREAD

**Issue by zhangweichina111** [skanzariya/Memwatch#2]
dear skanzariya:
when i use MemWatch,it print nothing. Then i read the code, i found there is a little code:strcmp(cmd,AppName).  I write a code in my phone, then i run in my phone.in /pro/pid/cmdline,there is nothing in it. I think Menmwatch will be invalid. 
thanks;

**Comment by skanzariya** [comment]
Memwatch uses command line argument for AppName.

**Comment by skanzariya** [comment]
I have tested this code on Linux PCs and embedded device on x86 and ARM platform only, I have not tested it on phone. It will be great if you can provide fix if you fount it.

**Comment by zhangweichina111** [comment]
some process has no cmdlins， for now I have no idea~
I will try~~

**Comment by skanzariya** [comment]
Thank You.

**Comment by skanzariya** [comment]
query answered.
